const AUTH = {
    CHECK_USERNAME: 'CHECK_USERNAME',

    LOCAL_REGISTER_PRIOR: 'LOCAL_REGISTER_PRIOR',
    LOCAL_REGISTER: 'LOCAL_REGISTER',

    LOCAL_LOGIN: 'LOCAL_LOGIN',

    OAUTH_CHECK: 'OAUTH_CHECK',
    OAUTH_REGISTER: 'OAUTH_REGISTER',

    CHECK_SESSION: 'CHECK_SESSION'
};

export default AUTH;