const CHANNEL = {
    INITIALIZE: 'CHANNEL_INITIALIZE',
    CHECK_VALIDITY: 'CHANNEL_CHECK_VALIDITY',
    SET_IDENTITY: 'SET_IDENTITY',
    SET_SOCKET_STATE: 'SET_SOCKET_STATE',
    RECEIVE_REALTIME_DATA: 'RECEIVE_REALTIME_DATA',
    WRITE_MESSAGE: 'WRITE_MESSAGE'
};

export default CHANNEL;