const CHANNEL = {
    INITIALIZE: 'CHANNEL_INITIALIZE',
    CHECK_INFO: 'CHANNEL_CHECK_INFO',
    SET_IDENTITY: 'SET_IDENTITY',
    SET_SOCKET_STATE: 'SET_SOCKET_STATE',
    RECEIVE_REALTIME_DATA: 'RECEIVE_REALTIME_DATA',
    WRITE_MESSAGE: 'WRITE_MESSAGE',
    MESSAGE_FAILURE: 'MESSAGE_FAILURE',
    REMOVE_MESSAGE: 'REMOVE_MESSAGE',

    SET_INITIAL_ONLINE_LIST: 'SET_INITIAL_ONLINE_LIST',
    ADD_ONLINE_USER: 'ADD_ONLINE_USER',
    REMOVE_ONLINE_USER: 'REMOVE_ONLINE_USER',



    GET_RECENT_MSG: 'GET_RECENT_MESSAGE',
    GET_MSG_BEFORE: 'GET_MSG_BEFORE',
    GET_MSG_BETWEEN: 'GET_MSG_BETWEEN',

    GET_STATUS_MSG: 'GET_STATUS_MESSAGE',

    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    GET_FOLLOWERS: 'GET_FOLLOWERS',
    GET_FOLLOWING: 'GET_FOLLOWING',
    CLEAR_USER_LIST: 'CLEAR_USER_LIST',

    SET_USER_LIST_INDEX: 'SET_USER_LIST_INDEX',
    TOGGLE_USER_INFO_FOLLOW_BUTTON: 'TOGGLE_USER_INFO_FOLLOW_BUTTON',
    FOLLOW_FROM_USER_LIST: 'FOLLOW_FROM_USER_LIST',
    UNFOLLOW_FROM_USER_LIST: 'UNFOLLOW_FROM_USER_LIST',

    ADD_FAVORITE: 'ADD_FAVORITE',
    DELETE_FAVORITE: 'DELETE_FAVORITE'
    
};

export default CHANNEL;