const EXPLORE = {
    INITIALIZE: 'EXPLORE_INITIALIZE',

    GET_INITIAL_ACTIVITY: 'GET_INITIAL_ACTIVITY',
    GET_ACTIVITY_BEFORE: 'GET_ACTIVITY_BEFORE',

    FOLLOW_FROM_ACTIVITY: 'FOLLOW_FROM_ACTIVITY',
    UNFOLLOW_FROM_ACTIVITY: 'UNFOLLOW_FROM_ACTIVITY',
    TOGGLE_FOLLOW_BUTTON_IN_ACTIVITY: 'TOGGLE_FOLLOW_BUTTON_IN_ACTIVITY',

    GET_RECENT_VISITS: 'GET_RECENT_VISITS'
}

export default EXPLORE;