const UI = {
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    SET_HEADER_TRANSPARENCY: 'SET_HEADER_TRANSPARENCY',
    SET_HEADER_BOUNDARY: 'SET_HEADER_BOUNDARY',
    SET_LIKE_TRANSPARENCY: 'SET_LIKE_TRANSPARENCY',
    SET_FOOTER_SPACE: 'SET_FOOTER_SPACE',
    SET_FOOTER_VISIBILITY: 'SET_FOOTER_VISIBILITY',
    SET_CHANNELBOX_STATE: 'SET_CHANNELBOX_STATE',
    SET_CHANNELCHAT_STATE: 'SET_CHANNELCHAT_STATE'
}

export default UI;