const UI = {
    INITIALIZE: 'UI_INITIALIZE',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    SET_HEADER_TRANSPARENCY: 'SET_HEADER_TRANSPARENCY',
    SET_HEADER_BOUNDARY: 'SET_HEADER_BOUNDARY',
    SET_LIKE_TRANSPARENCY: 'SET_LIKE_TRANSPARENCY',
    SET_FOOTER_SPACE: 'SET_FOOTER_SPACE',
    SET_FOOTER_VISIBILITY: 'SET_FOOTER_VISIBILITY',
    SET_CHANNELBOX_STATE: 'SET_CHANNELBOX_STATE',
    SET_CHANNELCHAT_STATE: 'SET_CHANNELCHAT_STATE',
    UPDATE_CLIENT_SIZE: 'UPDATE_CLIENT_SIZE',
    TOGGLE_FOCUS_BOX: 'TOGGLE_FOCUS_BOX',
    SHOW_FOCUS_BOX: 'SHOW_FOCUS_BOX',
    CLOSING_FOCUS_BOX: 'CLOSING_FOCUS_BOX',

    OPEN_EXPLORE: 'OPEN_EXPLORE',
    USER_SEARCH_TOGGLE: 'USER_SEARCH_TOGGLE',

    SELECT_LANGUAGE_TOGGLE: 'SELECT_LANGUAGE_TOGGLE',

    EDIT_PASSWORD_VISIBILITY_SET: 'EDIT_PASSWORD_VISIBILITY_SET'
}

export default UI;