/* AUTHENTICATION */

export const CHECK_USERNAME = 'CHECK_USERNAME';

export const LOCAL_REGISTER_PRIOR = 'LOCAL_REGISTER_PRIOR';
export const LOCAL_REGISTER = 'LOCAL_REGISTER';

export const LOCAL_LOGIN = 'LOCAL_LOGIN';

export const OAUTH_CHECK = 'OAUTH_CHECK';
export const OAUTH_REGISTER = 'OAUTH_REGISTER';

export const CHECK_SESSION = 'CHECK_SESSION';
