module.exports = {
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module",
        "allowImportExportEverywhere": false
    },
    "plugins": [
        "async-await"
    ],
    "rules": {
        "async-await/space-after-async": 2,
        "async-await/space-after-await": 2,
        'array-callback-return': 'warn',
            'default-case': ['warn', { commentPattern: '^no default$' }],
            'dot-location': ['warn', 'property'],
            'eqeqeq': ['warn', 'allow-null'],
            'guard-for-in': 'warn',
            'new-cap': ['warn', { newIsCap: true }],
            'new-parens': 'warn',
            'no-array-constructor': 'warn',
            'no-caller': 'warn',
            'no-cond-assign': ['warn', 'always'],
            'no-const-assign': 'warn',
            'no-control-regex': 'warn',
            'no-delete-var': 'warn',
            'no-dupe-args': 'warn',
            'no-dupe-class-members': 'warn',
            'no-dupe-keys': 'warn',
            'no-duplicate-case': 'warn',
            'no-empty-character-class': 'warn',
            'no-empty-pattern': 'warn',
            'no-eval': 'warn',
            'no-ex-assign': 'warn',
            'no-extend-native': 'warn',
            'no-extra-bind': 'warn',
            'no-extra-label': 'warn',
            'no-fallthrough': 'warn',
            'no-func-assign': 'warn',
            'no-implied-eval': 'warn',
            'no-invalid-regexp': 'warn',
            'no-iterator': 'warn',
            'no-label-var': 'warn',
            'no-labels': ['warn', { allowLoop: false, allowSwitch: false }],
            'no-lone-blocks': 'warn',
            'no-loop-func': 'warn',
            'no-mixed-operators': ['warn', {
              groups: [
                ['&', '|', '^', '~', '<<', '>>', '>>>'],
                ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
                ['&&', '||'],
                ['in', 'instanceof']
              ],
              allowSamePrecedence: false
            }],
            'no-multi-str': 'warn',
            'no-native-reassign': 'warn',
            'no-negated-in-lhs': 'warn',
            'no-new-func': 'warn',
            'no-new-object': 'warn',
            'no-new-symbol': 'warn',
            'no-new-wrappers': 'warn',
            'no-obj-calls': 'warn',
            'no-octal': 'warn',
            'no-octal-escape': 'warn',
            'no-redeclare': 'warn',
            'no-regex-spaces': 'warn',
            'no-restricted-syntax': [
              'warn',
              'LabeledStatement',
              'WithStatement'
            ],
            'no-return-assign': 'warn',
            'no-script-url': 'warn',
            'no-self-assign': 'warn',
            'no-self-compare': 'warn',
            'no-sequences': 'warn',
            'no-shadow-restricted-names': 'warn',
            'no-sparse-arrays': 'warn',
            'no-this-before-super': 'warn',
            'no-throw-literal': 'warn',
            'no-undef': 'warn',
            'no-unexpected-multiline': 'warn',
            'no-unreachable': 'warn',
            'no-unused-expressions': 'warn',
            'no-unused-labels': 'warn',
            'no-unused-vars': ['warn', { vars: 'local', args: 'none' }],
            'no-use-before-define': ['warn', 'nofunc'],
            'no-useless-computed-key': 'warn',
            'no-useless-concat': 'warn',
            'no-useless-constructor': 'warn',
            'no-useless-escape': 'warn',
            'no-useless-rename': ['warn', {
              ignoreDestructuring: false,
              ignoreImport: false,
              ignoreExport: false
            }],
            'no-with': 'warn',
            'no-whitespace-before-property': 'warn',
            'operator-assignment': ['warn', 'always'],
            radix: 'warn',
            'require-yield': 'warn',
            'rest-spread-spacing': ['warn', 'never'],
            strict: ['warn', 'never'],
            'unicode-bom': ['warn', 'never'],
            'use-isnan': 'warn',
            'valid-typeof': 'warn'
    }
};
